### PR TITLE
Use helpr module to run the command to display the output in case of an error

### PR DESCRIPTION
**Pull request by farzadmf**
I tried to run the new code and it was failing silently.

I added my own helper module to run the command because that's what I use every day, and it does the job for me. Feel free to change to something else if you think that's not good :slightly_smiling_face:

### CODE REVIEW

**Comment by kjellkvinge** [comment]
Thank you.

We need to show test output #7 seems to fix this as well. I started on some log-parsing to add some colors to test output, but for now I add this so it at least show the test logg:)

**Comment by farzadmf** [comment]
There seems to be a merge conflict :thinking: is it my fault?

**Comment by kjellkvinge** [comment]
no, not your fault. It was probably when I accepted #2

**Comment by farzadmf** [comment]
OK, cool, I can resolve the conflict then

**Comment by farzadmf** [comment]
Fixed the merge conflict, @kjellkvinge let me know if there's anything else :slightly_smiling_face:

**Comment by kjellkvinge** [comment]
Thank you for contributing and fixing the conflict. I really appreciate it 😃 

How would this work compared to #7 ? - Your PR would add a few dependencies to the project, and the utility function goutils.RunCommand depends on bash. I have not tested, but I was hoping this project (gocover) would work on windows,mac and linux.

regards

**Comment by farzadmf** [comment]
That's very true @kjellkvinge , good point; I'm using my thing only in Linux, so had forgotten about the `bash` dependency.

I guess we can close this and merge the other PR 

As long as it works, I don't care if it's my PR or not :slightly_smiling_face: . I had an alias for doing a "go cover", but your project displays the output way more interesting, and the reason for my PR(s) was to replace my alias with your project

**Pull request closed without merging**
