### PR TITLE
Create in the temp directory if the file name is the default

### PR DESCRIPTION
**Pull request by farzadmf**

### CODE REVIEW

**Comment by kjellkvinge** [comment]
Thank you.

To reach this code block where temp directory is used now (before this patch), one would have to pass `-coverFilename=""`

maybe it is better to change the default value of `fcoverFilename` to empty string?

like:

```diff
diff --git a/main.go b/main.go
index 30e1f85..7cfdadd 100644
--- a/main.go
+++ b/main.go
@@ -29,7 +29,7 @@ var from = pterm.NewRGB(171, 200, 170)
 func main() {
        flag.StringVar(&fFunc, "func", "", "Show only selected function")
        flag.StringVar(&fFileName, "file", "", "show anotatded sourcecode for selected file")
-       flag.StringVar(&fcoverFilename, "coverFilename", "coverage.out", "Cover profile filename location")
+       flag.StringVar(&fcoverFilename, "coverFilename", "", "Cover profile filename location")
        flag.BoolVar(&fLegend, "legend", false, "Print sample colors")
        flag.BoolVar(&fRunTests, "runtests", true, "Run tests and generate coverage profile")
        flag.Parse()

```



What do you think?

Best regards

**Comment by farzadmf** [comment]
Yes, I think that's a good idea. I didn't want to change the existing flag setup, so that didn't come to my mind.

Updated my PR with your suggestion.

Also, on a side note, I'm curious about how you do that diff in your comment 😝

**Comment by kjellkvinge** [comment]
thank you. regarding that diff in my comment. not sure if you as how I created it, or how I presented it?
It is a sandard diff output you can create using the command `diff -b oldfile newfile` or, when working with git - running `git diff` or `git diff filename`

when presenting something like that in github, you can put it in a code block like this:

    ```diff
    patch here
    ```

funfact: For a long time, this was the workflow for maintaining the linux kernel - generate a patch and send it by email. 
Hope that answered your question :)

**Comment by farzadmf** [comment]
Thank you @kjellkvinge , yes that answered my question. The nice tip that I didn't know was that we can have a `diff` format for a code block.

And thank you for the fun fact; so interesting. I guess that's why Linus created `git` to make all our lives easier :wink:

**Pull request merged**
